### PR TITLE
Switch to Rails 4

### PR DESCRIPTION
**Pull request by darrencauthon**
So here's how I did it:  
1. Started a new Rails app with Rails 4.1 RC1.
2. Brought in the existing code.
3. Fixed the obviously broken stuff.
4. Removed the omniauth stuff.

### CODE REVIEW

**Comment by darrencauthon** [comment]
I deleted all of the stubbed tests, too.

**Comment by darrencauthon** [comment]
@HolyCow This PR upgrades this website to Rails4 and Ruby 2.1.  How should this change affect the Vagrant work?  (especially the Cheffile?)

**Comment by MikeBeasterfeld** [comment]
I think the only changed need to happen to customcookbooks/kcruby/recipies/default.rb.  Update 'ruby_verion' and sounds like remove the omniauth file copy.  'config/omniauth.yml.example' can also be removed.

I can make and test the changes, but I'm not familiar enough with git to know the best way to contribute that.  With a little guidance I'm happy to do it.

**Comment by darrencauthon** [comment]
@HolyCow I can do that in a bit, I don't mean to dump more work on you. :smile: 

Technically, I think the way to contribute that change is to fork darrencauthon/kcruby, check out the "switch_to_rails_4" branch, and then issue a pull request from yours into the "switch_to_rails_4" branch.  I can accept the pull request, which will add your code to this pull request. 

Or.... let me try this....

**Comment by darrencauthon** [comment]
I added you as a collaborator to darrencauthon/kcruby.  So you can checkout this branch and push directly to it.

**Comment by darrencauthon** [comment]
The existing site runs on the Bamboo stack, but we have to be on the Cedar stack in order to run the app.  And the only way to make that sort of move is to create a new app.

I've done so and pushed up to:

http://calm-peak-7395.herokuapp.com

**Pull request closed without merging**
